"""The advisory layer: readings that never bid on a pick.

Three separate things live here, and they share exactly one property — none of
them may ever enter the suggestion score or the survival math. That boundary is
the whole reason the module exists apart from `draft.py`:

- **Bye and same-team findings.** A bye penalty inside the pick score would
  trade real season points for cosmetic tidiness; in a 12-team league with
  waivers, one bad week is streamable. Same-team exposure is a variance story,
  not an expected-points story. Both get shown on the shelf; neither bids.

- **Position pressure.** The residual — picks taken at a position minus what
  ADP said that pick range would take — and NOT a raw count of positions in a
  window. Measured 2026-08-26 against a draft generated by twelve independent
  ADP-followers (demo's opponent AI is lowest-ADP + gauss(0,4)), i.e. a draft
  with no runs in it by construction: a "4 of the last 10" counter fired in
  95.9% of windows, and 57.1% at "5 of 10", because position mix and the shape
  of the ADP curve cluster on their own. The residual on that same draft is
  centred at 0.00 with sd 1.02 and — at the calibrated threshold of 4 — fires
  in 2.9% of windows against the counter's 95.9%. The count detector mostly
  measures the ADP curve, and survival is ALREADY computed from ADP, so
  feeding it back in would double-count the same structure and call it new
  information. Hence: display only, until the threshold has been calibrated
  against a real room's drafts. Threshold lives in config as
  RUN_RESIDUAL_THRESHOLD, with the full calibration table beside it.

- **League priors.** Plain-English readings of the room's own rules. The engine
  already absorbs all of this through scoring-calibrated VBD; these lines only
  say out loud what the math is doing.
"""
from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import Any

from ..config import RUN_RESIDUAL_THRESHOLD

# Slot vocabulary shared with Sleeper. A SUPER_FLEX is its own thing (it eats
# quarterbacks) but for "can I fill a lineup" purposes every flex is a flex.
_BENCH = ("BN", "IR", "TAXI")
_FLEX_SLOTS = ("FLEX", "SUPER_FLEX", "SUPERFLEX", "WRRB_FLEX", "REC_FLEX")
_DEDICATED = ("QB", "RB", "WR", "TE", "K", "DEF")
# Correlation lives among the skill positions. A kicker and a defense from the
# same club as one of your receivers is not a bet worth a warning.
_SKILL = ("QB", "RB", "WR", "TE")
_CATCHERS = ("WR", "TE")
# Three men out in one week is worth knowing even when every slot still fills.
_CROWDED_BYE = 3
# Rostering this many from one club is a correlated Sunday.
_TEAM_EXPOSURE = 3


@dataclass(frozen=True)
class Finding:
    """One reading. `label` is the chip; `detail` is the line under it."""
    kind: str    # bye | backfield | stack | team
    level: str   # info | warn
    label: str
    detail: str

    def as_dict(self) -> dict[str, str]:
        return {"kind": self.kind, "level": self.level,
                "label": self.label, "detail": self.detail}


def starting_slots(roster_positions: list[str]) -> dict[str, int]:
    """Dedicated starter slots per position, with every flavour of flex
    collapsed into one FLEX count. Bench slots never appear."""
    slots: dict[str, int] = {}
    for s in roster_positions:
        if s in _BENCH:
            continue
        key = "FLEX" if s in _FLEX_SLOTS else s
        slots[key] = slots.get(key, 0) + 1
    return slots


def _bye_findings(roster: list[dict[str, Any]],
                  slots: dict[str, int]) -> list[Finding]:
    """Weeks the shelf thins out. A week that both empties a starter slot and
    is crowded says it once — the slot break is the louder half."""
    have = Counter(p["pos"] for p in roster)
    by_week: dict[int, list[dict]] = defaultdict(list)
    for p in roster:
        if p.get("bye"):
            by_week[int(p["bye"])].append(p)

    out: list[Finding] = []
    for week in sorted(by_week):
        gone = by_week[week]
        out_at = Counter(p["pos"] for p in gone)
        # Which dedicated slots the BYE breaks. All three conditions matter:
        # the position must be fillable in a normal week, unfillable in this
        # one, and it must be the bye that did it. Without the first clause a
        # half-drafted shelf reports "QB goes empty" in every week of the
        # season — an unfilled slot is the shelf counters' story, not a bye's.
        # FLEX is excluded throughout: it takes any of RB/WR/TE and refills
        # itself.
        broken = [pos for pos in _DEDICATED
                  if slots.get(pos, 0) and out_at[pos]
                  and have[pos] >= slots[pos]
                  and have[pos] - out_at[pos] < slots[pos]]
        if broken:
            spread = " and ".join(broken)
            out.append(Finding(
                "bye", "warn", f"WK {week}",
                f"{spread} goes empty in week {week} — "
                f"{len(gone)} of your men are out."))
        elif len(gone) >= _CROWDED_BYE:
            out.append(Finding(
                "bye", "info", f"WK {week}",
                f"{len(gone)} of your men sit out week {week}."))
    return out


def _team_findings(roster: list[dict[str, Any]]) -> list[Finding]:
    """Where the shelf is doubled up on one club's Sunday."""
    by_team: dict[str, list[dict]] = defaultdict(list)
    for p in roster:
        if p.get("team") and p["pos"] in _SKILL:
            by_team[p["team"]].append(p)

    out: list[Finding] = []
    for team in sorted(by_team):
        group = by_team[team]
        if len(group) < 2:
            continue
        backs = [p["name"] for p in group if p["pos"] == "RB"]
        if len(backs) >= 2:
            out.append(Finding(
                "backfield", "warn", team,
                f"{' and '.join(backs)} split the same carries."))
        qbs = [p["name"] for p in group if p["pos"] == "QB"]
        catchers = [p["name"] for p in group if p["pos"] in _CATCHERS]
        if qbs and catchers:
            out.append(Finding(
                "stack", "info", team,
                f"{qbs[0]} throwing to {catchers[0]} — one good afternoon "
                f"pays twice."))
        if len(group) >= _TEAM_EXPOSURE:
            out.append(Finding(
                "team", "warn", team,
                f"{len(group)} {team} men on the shelf — their bad Sunday "
                f"is your bad Sunday."))
    return out


def shelf_findings(roster: list[dict[str, Any]],
                   slots: dict[str, int]) -> dict[str, Any]:
    """Everything the shelf has to say about itself.

    `roster` rows need pos / name / team / bye. `byes_known` is load-bearing:
    the Sleeper feed ships no byes at all (they are backfilled onto players
    from the persisted nfl_games table), so a roster with a null bye must read
    as UNKNOWN, never as clean. A silent all-clear is the one failure this
    house does not allow.
    """
    return {
        "findings": _bye_findings(roster, slots) + _team_findings(roster),
        "byes_known": all(p.get("bye") for p in roster),
    }


def position_pressure(observed: dict[str, int], expected: dict[str, float],
                      threshold: float = RUN_RESIDUAL_THRESHOLD
                      ) -> list[dict[str, Any]]:
    """Positions the room is taking faster ("run") or slower ("slide") than the
    market said it would, over one window of picks.

    residual = observed − ADP-expected across the same pick range, so a room
    that drafts to ADP produces silence. See the module docstring for why the
    obvious alternative — counting positions in the window — is noise.
    """
    out: list[dict[str, Any]] = []
    for pos in list(observed) + [p for p in expected if p not in observed]:
        residual = observed.get(pos, 0) - expected.get(pos, 0.0)
        if abs(residual) < threshold:
            continue
        out.append({
            "pos": pos,
            "observed": observed.get(pos, 0),
            "expected": round(expected.get(pos, 0.0), 1),
            "residual": round(residual, 1),
            "direction": "run" if residual > 0 else "slide",
        })
    out.sort(key=lambda r: -abs(r["residual"]))
    return out


def league_priors(scoring: dict[str, Any], roster_positions: list[str],
                  teams: int) -> list[str]:
    """What this room's own rules do to positional priority, in words.

    The board's math already accounts for every one of these through
    scoring-calibrated VBD — these lines just say it out loud. Capped at three:
    the board is dense on purpose and this is the least urgent thing on it.
    """
    slots = starting_slots(roster_positions)
    rec = scoring.get("rec", 1.0)
    lines: list[str] = []

    if any(s in ("SUPER_FLEX", "SUPERFLEX") for s in roster_positions):
        lines.append("Superflex: quarterbacks are the scarce good — this room "
                     "takes them early and you cannot wait them out.")
    if rec == 0:
        lines.append("Standard scoring: catches pay nothing. Volume runners "
                     "keep their value; possession receivers lose theirs.")
    elif rec and rec < 1.0:
        lines.append("Half-PPR: catches pay half. Receivers and pass-catching "
                     "backs float up, but not to full-PPR heights.")
    else:
        lines.append("Full PPR: every catch is a point. Receivers and "
                     "pass-catching backs float up the board.")
    # SUPER_FLEX is deliberately excluded — it eats quarterbacks, not receivers.
    wr_seats = slots.get("WR", 0) + sum(
        1 for s in roster_positions if s in ("FLEX", "WRRB_FLEX", "REC_FLEX"))
    if wr_seats >= 3:
        lines.append(f"{wr_seats} WR/FLEX seats: receiver demand runs deeper "
                     f"than the raw ranks suggest.")
    if teams >= 14:
        lines.append(f"{teams} teams: scarcity arrives early and the waiver "
                     f"pool is picked over.")
    elif teams <= 8:
        lines.append(f"{teams} teams: scarcity is mild — real replacement "
                     f"talent stays on the board all night.")
    if scoring.get("pass_td", 4.0) >= 6:
        lines.append("Passing TDs at 6: pocket quarterbacks get a bump.")
    return lines[:3]
